### ISSUE TITLE
Mustached attributes don't really stand out

### ISSUE THREAD

**Issue by alextreppass** [adamchainz/SublimeHTMLMustache#9] opened 2015-04-08 14:51 UTC
![screen shot 2015-04-08 at 15 47 01](https://cloud.githubusercontent.com/assets/154376/7047820/eb7a7f7c-de06-11e4-84f5-cc2f540e4875.png)

This may be by design, but I think it would be great for the `{{someUrl}}` attribute to stand out the same way the `{{someText}}` in the above example does.

Thoughts?

**Comment by alextreppass** [comment] 2015-04-08 14:52
Oh, maybe this is a duplicate of /adamchainz/SublimeHTMLMustache/issues/7

**Comment by adamchainz** [comment] 2015-04-08 18:56
Duplicate of #7 indeed!

**Closed by adamchainz** 2015-04-08 18:56 UTC
